name: CD
on:
  push:
    branches:
    - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: alexsouzasilva
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v1.1.0
      with:
        username: alexsouzasilva
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: alexsouzasilva/kube-argo-kust
        tags: ${{ github.sha }}, latest

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: kustomize
      uses: imranismail/setup-kustomize@v1
      with:
        kustomize_version: v3.6.1

    - name: update k8s
      run: |
        cd k8s
        kustomize edit set image kube-argo-kust=alexsouzasilva/kube-argo-kust:${{ github.sha }}
        cat kustomization.yaml

    - name: commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "Deploy Action"
        git commit -am "change image tag"

    - name: push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}




